#!/bin/bash

source setup-functions

##
## template file names
##
app_name=app

# @todo standalone to service
template_path=samples/service.yml
config_file=containers/$app_name.yml
changelog=/tmp/changelog

##
## Check requirements before creating a copy of a config file we won't edit
##
check_root
check_and_install_docker
check_disk_and_memory

# @todo clear check ports
check_ports

##
## make a copy of the simple standalone config file
##
if [ -a $config_file ]
then
  echo "The configuration file $config_file already exists!"
  echo ""
  echo "If you want to delete your old configuration file and start over:"
  echo "rm $config_file"
  #todo clear this line
  rm -fr $config_file;
  exit 1
else
  cp $template_path $config_file
  echo "${template_path} copied ${config_file}";
fi

scale_ram_and_cpu
ask_user_for_config
validate_config

##
## if we reach this point without exiting, OK to proceed
##
#./launcher bootstrap $app_name && ./launcher start $app_name

./runner bootstrap $app_name